{% set name = "ecodata" %}
{% set version = "2.7.0dev" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../ecodata


build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python >3.10
    - pip
  run:
    - python >3.10
    - cartopy
    - geopandas
    - matplotlib
    - pandas
    - shapely <2.0
    - xarray
    - dask
    - netCDF4
    - bottleneck
    - cfgrib
    - rasterio
    - numpy <1.24
    - rioxarray
    - hvplot
    - bokeh <3.4
    - panel >=1,<1.4
    - datashader
    - geoviews >=1.10
    - geocube
    - ffmpeg
    - gdown <4.6

test:
  imports:
    - ecodata

about:
  home: https://palletsprojects.com/p/click/
  license: BSD
  license_family: BSD
  summary: Composable command line interface toolkit
